name: Test-Workflow

run-name: Build ${{ github.actor }}/${{ github.ref_name }}

on: [push]

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  install-deps:
    needs: [checkout-repo]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
  lint:
    needs: [install-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Lint project
        run: npm run lint
  test:
    needs: [install-deps]
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        run: npm run test
  # Test-Job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run integration test using npm run test
  #       run: npm run test
  #     - run: echo "ğŸ This job's status is ${{ job.status }}."
